In [1]:
from pyspark.context import SparkContext
from awsglue.context import GlueContext

glue = GlueContext(SparkContext.getOrCreate())

In [2]:
crimes = glue.create_dynamic_frame.from_catalog("jnme-ab3-v1-clean", "crimes", transformation_ctx="source")

In [4]:
crimes.toDF().limit(10).toPandas().head(10)

,id,case_number,date,block,iucr,primary_type,description,location_description,arrest,domestic,...,ward,community_area,fbi_code,x_coordinate,y_coordinate,updated_on,latitude,longitude,location,year
0,9742058,HX392289,2014-07-16 10:00:00,115XX W TOUHY AVE,0820,THEFT,$500 AND UNDER,PARKING LOT/GARAGE(NON.RESID.),False,False,...,41.0,76,06,1100260.0,1946117.0,2018-02-10 15:50:01,42.008885,-87.906473,"(42.008885217, -87.906473187)",2014
1,9819178,HX468762,2014-10-15 13:30:00,069XX N CENTRAL AVE,1153,DECEPTIVE PRACTICE,FINANCIAL IDENTITY THEFT OVER $ 300,APARTMENT,False,False,...,41.0,12,11,1139606.0,1945641.0,2018-02-10 15:50:01,42.006949,-87.761717,"(42.006949411, -87.761716897)",2014
2,9827727,HX464897,2014-10-12 14:30:00,065XX N MANNHEIM RD,1320,CRIMINAL DAMAGE,TO VEHICLE,STREET,False,False,...,NaN,76,14,1106263.0,1941939.0,2020-05-08 15:48:21,41.997336,-87.884466,"(41.997336014, -87.884466308)",2014
3,10809893,JA109211,2006-12-30 14:00:00,031XX W ROOSEVELT RD,1153,DECEPTIVE PRACTICE,FINANCIAL IDENTITY THEFT OVER $ 300,APARTMENT,False,False,...,24.0,29,11,NaN,NaN,2017-01-14 15:49:38,NaN,NaN,,2006
4,10992846,JA319757,2006-11-28 00:00:00,032XX W FULTON BLVD,1153,DECEPTIVE PRACTICE,FINANCIAL IDENTITY THEFT OVER $ 300,APARTMENT,False,False,...,28.0,27,11,NaN,NaN,2017-06-24 15:50:57,NaN,NaN,,2006
5,11339107,JB295436,2006-09-01 00:01:00,028XX W JACKSON BLVD,1153,DECEPTIVE PRACTICE,FINANCIAL IDENTITY THEFT OVER $ 300,RESIDENCE,False,False,...,27.0,27,11,NaN,NaN,2018-10-27 16:00:07,NaN,NaN,,2006
6,11345360,JB303675,2006-06-01 00:00:00,031XX W MONROE ST,1153,DECEPTIVE PRACTICE,FINANCIAL IDENTITY THEFT OVER $ 300,RESIDENCE,False,False,...,28.0,27,11,NaN,NaN,2018-06-16 15:51:19,NaN,NaN,,2006
7,11422600,JB404529,2006-08-01 00:01:00,002XX N KEYSTONE AVE,1153,DECEPTIVE PRACTICE,FINANCIAL IDENTITY THEFT OVER $ 300,RESIDENCE,False,False,...,28.0,26,11,NaN,NaN,2018-08-25 15:59:23,NaN,NaN,,2006
8,3487,HM154020,2006-01-30 19:10:00,011XX N KEELER AVE,0110,HOMICIDE,FIRST DEGREE MURDER,GARAGE,True,False,...,37.0,23,01A,1148166.0,1907481.0,2019-03-19 16:11:22,41.902074,-87.731209,"(41.902074239, -87.731209331)",2006
9,3488,HM154020,2006-01-30 22:15:00,011XX N KEELER AVE,0110,HOMICIDE,FIRST DEGREE MURDER,GARAGE,True,False,...,37.0,23,01A,1148166.0,1907481.0,2019-03-19 16:11:22,41.902074,-87.731209,"(41.902074239, -87.731209331)",2006